[package]
name = "tex_rules"
version = "0.1.0"
authors = ["Hilmar Gústafsson <hilmargustafs@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
memmem = "0.1.1"
glob = "0.3.0"
anyhow = "1.0.0"